
{!! Html::style('assets/bootstrap/dist/css/bootstrap.min.css') !!}
{!! Html::style('assets/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css') !!}
{!! Html::style('css/sb-admin-2.css') !!}
{!! Html::style('assets/font-awesome/css/font-awesome.min.css') !!}
{!! Html::style('assets/bootstrap-star-rating/css/theme-krajee-fa.min.css') !!}
{!! Html::style('assets/bootstrap-star-rating/css/theme-krajee-fa.css') !!}
{!! Html::style('assets/bootstrap-star-rating/css/theme-krajee-svg.css') !!}
{!! Html::style('assets/bootstrap-star-rating/css/theme-krajee-uni.css') !!}
{!! Html::style('assets/bootstrap-star-rating/css/star-rating.css') !!}
{!! Html::style('assets/metisMenu/dist/metisMenu.min.css') !!}
{!! Html::style('assets/datatables-responsive/css/responsive.dataTables.css') !!}
{!! Html::style('css/profile.css') !!}
{!! Html::style('css/plugins.css') !!}
{!! Html::style('css/main.css') !!}
{!! Html::style('css/themes.css') !!}
{!! Html::style('css/product.css') !!}
{!! Html::style('css/home.css') !!}
{!! Html::style('css/contact.css') !!}
